import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "SoftQA",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  }
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <Navbar />
        <main>{children}</main>
        <Footer />
    </>
  );
}
