import "./custom.css"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SoftQA",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  }
};

export default function SignInLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}