import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/layout/navbar";

export const metadata: Metadata = {
  title: "SoftQA",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-normal"
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
