import type { Metadata } from "next";
import "./globals.css";
import MainClientLayout from "./main-layout"; 

export const metadata: Metadata = {
  title: "SoftQA",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainClientLayout>
          {children}
        </MainClientLayout>
      </body>
    </html>
  );
}